services:
    # Support manager
    innova_support.manager.support:
        class: %innova_support.manager.support.class%
        arguments:
            securityContext: @security.context
            mailer:          @mailer